In [1]:
import numpy as np
from sklearn.datasets import load_breast_cancer

data = load_breast_cancer()
X = data.data
y = data.target

In [2]:
from sklearn.model_selection import ShuffleSplit
ss = ShuffleSplit(n_splits=1, train_size=0.8, test_size=0.2,
                  random_state=0)

train_index, test_index = next(ss.split(X,y))

X_train, X_test = X[train_index], X[test_index]
y_train, y_test = y[train_index], y[test_index]

In [3]:
from sklearn import linear_model
clf = linear_model.LogisticRegression()

In [4]:
clf.fit(X_train, y_train)

/home/ma/.bin/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [5]:
y_pred = clf.predict(X_test)

In [6]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [7]:
accuracy_score(y_test, y_pred)

0.956140350877193

In [8]:
clf.decision_function(X_test[12:15])

array([ 5.52621662, -1.17704943,  1.40199302])

In [9]:
clf.predict(X_test[12:15])

array([1, 0, 1])

In [10]:
(clf.decision_function(X_test[12:15])>0).astype(int)

array([1, 0, 1])